Areas/Hidden/Controllers/ContentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication.Models;

namespace WebApplication.Areas.Hidden.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ContentsController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Hidden/Contents
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ByFeed(string url)
        {
            return View(db.Contents.Where(a => a.Feed.Url == url).ToList());
        }
    }
}

Areas/Hidden/Controllers/FeedsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication.Areas.Hidden.Models;
using WebApplication.Models;

namespace WebApplication.Areas.Hidden.Controllers
{
    [Authorize(Roles = "Admin")]
    public class FeedsController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Hidden/Feeds
        public ActionResult Index()
        {
            DateTime last = DateTime.Now.AddDays(-2);
            List<Feed> feeds = db.Feeds.Where(a => a.CreateDate >= last && a.DoNotUpdate == false).ToList();
            ViewBag.Feeds = feeds;

            return View(new FeedSortParams()
            {
                Domain = null,
                CreationDateStart = last,
                CreationDateEnd = DateTime.Now,
                DoNotUpdate = false
            });

        }

        [HttpPost]
        public ActionResult Index([Bind(Include = "Domain,CreationDateStart,CreationDateEnd,DoNotUpdate")]FeedSortParams param)
        {
            var query = db.Feeds.Where(a => a.DoNotUpdate == param.DoNotUpdate);

            if (!String.IsNullOrWhiteSpace(param.Domain))
            {
                query = query.Where(a => a.Domain.Host == param.Domain.ToLower());
            }

            if (param.CreationDateStart != null)
            {
                query = query.Where(a => a.CreateDate >= param.CreationDateStart);
            }

            if (param.CreationDateEnd != null)
            {
                query = query.Where(a => a.CreateDate <= param.CreationDateEnd);
            }

            List<Feed> feeds = query.ToList();
            ViewBag.Feeds = feeds;

            return View(param);
        }

        public ActionResult ByTag(string id)
        {

            List<Feed> feeds = db.Feeds.Where(a => a.Tag.Id == id).ToList();
            return View(feeds);
        }

        public ActionResult ByDomain(string host)
        {
            List<Feed> feeds = db.Feeds.Where(a => a.Domain.Host == host).ToList();
            return View(feeds);
        }

        public ActionResult Contents(string url)
        {
            return View(db.Contents.Where(a => a.Feed.Url == url).ToList());
        }

        // GET: Hidden/Feeds/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Hidden/Feeds/Create
        public ActionResult Create()
        {
            ViewBag.Tags = db.Tags.Where(a => a.Visible == true && a.Feeds.Any(b => b.DoNotUpdate == false && a.ParentTags.Count == 0)).ToList();
            ViewBag.Langs = db.Languages.ToList();
            return View();
        }

        [HttpPost]
        public ActionResult Create(string url, string title, string language, bool donotupdate, string tag)
        {
            ViewBag.Tags = db.Tags.Where(a => a.Visible == true && a.Feeds.Any(b => b.DoNotUpdate == false && a.ParentTags.Count == 0)).ToList();
            ViewBag.Langs = db.Languages.ToList();

            if (String.IsNullOrWhiteSpace(url) || String.IsNullOrWhiteSpace(title) || String.IsNullOrWhiteSpace(language) || String.IsNullOrWhiteSpace(tag))
            {
                ViewBag.Message = "Все параметры должны быть заданы";
                return View();
            }

            Uri uri = null;
            if (!Uri.TryCreate(url, UriKind.Absolute, out uri))
            {
                ViewBag.Message = "Невозможно создать Uri";
                return View();
            }

            DateTime now = DateTime.Now;
            Feed newFeed = new Feed();

            newFeed.UriScheme = uri.Scheme;
            newFeed.Url = uri.Host + uri.PathAndQuery;
            newFeed.Title = title;
            newFeed.Language = language;
            newFeed.DoNotUpdate = donotupdate;

            newFeed.LastCheckTime = now;
            newFeed.LastUpdateTime = now;
            newFeed.Rating = 0;
            newFeed.CreateDate = now;
            newFeed.Failures = 0;

            Domain domain = db.Domains.Find(uri.Host);
            if (domain == null)
            {
                ViewBag.Message = String.Format("Домена {0} нет в базе", uri.Host);
                return View();
            }

            Tag existTag = null;

            if (!String.IsNullOrWhiteSpace(tag))
            {
                existTag = db.Tags.FirstOrDefault(a => a.Id == tag);
                if (existTag == null)
                {
                    existTag = db.Tags.Add(new Tag()
                    {
                        Id = tag,
                        CreationDate = now,
                        Title = newFeed.Title,
                        Visible = true
                    });
                }
            }
            else
            {
                return View();
            }

            newFeed.Domain = domain;
            newFeed.Tag = existTag;
            newFeed.TextLanguage = db.Languages.Find(language);

            db.Feeds.Add(newFeed);
            db.SaveChanges();

            ViewBag.Message = String.Format("Источник {0} Успешно добавлен.", uri.AbsoluteUri);
            return View();
        }

        // GET: Hidden/Feeds/Edit/5
        public ActionResult Edit(string url)
        {
            Feed feed = db.Feeds.Find(url);
            ViewBag.Tag = feed.Tag;
            ViewBag.Tags = db.Tags.Where(a => a.Visible == true);
            ViewBag.Languages = db.Languages.ToList();// select new SelectListItem { Text = lang.RussianName, Value = lang.Id };
            return View(feed);
        }

        // POST: Hidden/Feeds/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "Url,Title,Description,Language,Comment,Block,Failures,Rating,DoNotUpdate,Tag_Id")] Feed feed)
        {

            Feed uFeed = db.Feeds.Find(feed.Url);
            uFeed.Title = feed.Title;
            uFeed.Language = feed.Language;
            uFeed.Description = feed.Description;
            uFeed.Comment = feed.Comment;
            uFeed.Block = feed.Block;
            uFeed.Failures = feed.Failures;
            uFeed.Rating = feed.Rating;
            uFeed.Tag_Id = feed.Tag_Id;
            uFeed.Tag = db.Tags.Find(feed.Tag_Id);
            uFeed.DoNotUpdate = feed.DoNotUpdate;
            db.SaveChanges();

            ViewBag.Tag = uFeed.Tag;
            ViewBag.Tags = db.Tags.Where(a => a.Visible == true);
            ViewBag.Languages = db.Languages.ToList();
            return View(feed);
        }

        // GET: Hidden/Feeds/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Hidden/Feeds/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public bool ChangeUpdateStatus(string url,bool doNotUpdate)
        {
            Feed feed = db.Feeds.FirstOrDefault(a => a.Url == url);
            if(feed != null)
            {
                feed.DoNotUpdate = doNotUpdate;
                db.SaveChanges();
                return true;
            }
            return false;
        }
    }
}

Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using WebApplication.Core;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using WebApplication.Models;
using System.Data.Entity;
using System.Threading;

namespace WebApplication.Controllers
{
    public class TagsController : Controller
    {
        private AppCache _cache = null;
        private readonly int _maxContentCount = 0;

        public TagsController()
        {
            _maxContentCount = 30;
            _cache = new AppCache();
        }

        // POST : Newest
        [HttpPost]
        public async Task<JsonResult> Newest(string tag,string lang, int skip)
        {
            ContentItem[] items = new ContentItem[0];
            if (!String.IsNullOrWhiteSpace(tag) && !Utils.IsCorrectTagName(tag)) return Json(items);
            if (lang.Length > 3) return Json(items);

            string cacheKey = _cache.GenerateKey("Newest", tag, lang, skip);

            if (_cache.Contains(cacheKey))
            {
                items = _cache.Get(cacheKey);
            }
            else
            {
                if (String.IsNullOrWhiteSpace(tag))
                {
                    items = await ContentFromDB.AllContentOrderByTime(skip, _maxContentCount, lang);
                    _cache.Add(cacheKey, items, 360);
                }
                else {
                    items = await ContentFromDB.TagsContentOrderByTime(tag, lang, skip, _maxContentCount);
                    _cache.Add(cacheKey, items, 360);
                }
            }

            return Json(items);
        }

        [HttpPost]
        public async Task<JsonResult> Today(string tag, string lang, int skip)
        {
            ContentItem[] items = new ContentItem[0];
            if (!String.IsNullOrWhiteSpace(tag) && !Utils.IsCorrectTagName(tag)) return Json(items);
            if (lang.Length > 3) return Json(items);

            string cacheKey = _cache.GenerateKey("Today", tag, lang, skip);

            if (_cache.Contains(cacheKey))
            {
                items = _cache.Get(cacheKey);
            }
            else
            {
                if (String.IsNullOrWhiteSpace(tag))
                {
                    items = await ContentFromDB.AllContentOrderByRating(skip, _maxContentCount, lang, DateTime.Now.AddDays(-1));
                    _cache.Add(cacheKey, items, 360);
                }
                else {
                    items = await ContentFromDB.TagsContentOrderByRating(tag, lang, skip, _maxContentCount, DateTime.Now.AddDays(-1));
                    _cache.Add(cacheKey, items, 360);
                }
            }
            return Json(items);
        }

        [HttpPost]
        public async Task<JsonResult> Weekly(string tag, string lang, int skip)
        {
            ContentItem[] items = new ContentItem[0];
            if (!String.IsNullOrWhiteSpace(tag) && !Utils.IsCorrectTagName(tag)) return Json(items);
            if (lang.Length > 3) return Json(items);

            string cacheKey = _cache.GenerateKey("Weekly", tag, lang, skip);

            if (_cache.Contains(cacheKey))
            {
                items = _cache.Get(cacheKey);
            }
            else
            {
                if (String.IsNullOrWhiteSpace(tag))
                {
                    items = await ContentFromDB.AllContentOrderByRating(skip, _maxContentCount, lang, DateTime.Now.AddDays(-7));
                    _cache.Add(cacheKey, items, 360);
                }
                else {
                    items = await ContentFromDB.TagsContentOrderByRating(tag, lang, skip, _maxContentCount, DateTime.Now.AddDays(-7));
                    _cache.Add(cacheKey, items, 360);
                }
            }
            return Json(items);
        }

        [HttpPost]
        public async Task<JsonResult> Monthy(string tag, string lang, int skip)
        {
            ContentItem[] items = new ContentItem[0];
            if (!String.IsNullOrWhiteSpace(tag) && !Utils.IsCorrectTagName(tag)) return Json(items);
            if (lang.Length > 3) return Json(items);

            string cacheKey = _cache.GenerateKey("Monthy", tag, lang, skip);

            if (_cache.Contains(cacheKey))
            {
                items = _cache.Get(cacheKey);
            }
            else
            {
                if (String.IsNullOrWhiteSpace(tag))
                {
                    items = await ContentFromDB.AllContentOrderByRating(skip, _maxContentCount, lang, DateTime.Now.AddDays(-30));
                    _cache.Add(cacheKey, items, 360);
                }
                else {
                   
                    items = await ContentFromDB.TagsContentOrderByRating(tag, lang, skip, _maxContentCount, DateTime.Now.AddDays(-30));
                    _cache.Add(cacheKey, items, 360);
                }
            }
            return Json(items);
        }

    }
}

Areas/Hidden/Views/Feeds/ByDomain.cshtml
@model IEnumerable<WebApplication.Models.Feed>

@*<table class="ui compact table">
    <tr>
        <th style="width:400px">
            Url
        </th>
        <th>
            Назв
        </th>
        <th>
            Не обнов
        </th>
        <th>
            Язык
        </th>
        <th>
            Пров-н
        </th>
        <th>
            Обновлен
        </th>
        <th>

        </th>
        <th class="right aligned"></th>
    </tr>

    @foreach (WebApplication.Models.Feed item in Model)
    {
        <tr>
            <td style="max-width:150px;">
                @Html.Raw(item.Url)
            </td>
            <td style="max-width:150px;">
                @Html.Raw(item.Title)
            </td>
            <td>
                <input name="visible" type="checkbox" @Html.Raw(item.DoNotUpdate ? "checked='checked'" : "") onclick="changeStatus(this)" data-type=@Html.Raw(item.Url)>
            </td>
            <td>
                @Html.Raw(item.Language)
            </td>
            <td>
                @Html.Raw(item.LastCheckTime)
            </td>
            <td>
                @Html.Raw(item.LastUpdateTime)
            </td>
            <td class="right aligned">
                @Html.ActionLink("Контент", "ByFeed", "Contents", new { url = item.Url }, new { @class = "ui teal basic tiny button" })
                @Html.ActionLink("Изменить", "Edit", new { url = item.Url }, new { @class = "ui teal basic tiny button" })
            </td>
        </tr>
    }

</table>
<script>
    function changeStatus(el) {
        var url = $(el).attr('data-type');
        var notUpdate = $(el).prop('checked');
        var headers = {};

        $.ajax({
            url: '/Hidden/Feeds/ChangeUpdateStatus',
            dataType: "json",
            type: "POST",
            headers: headers,
            data: JSON.stringify({
                "url": url,
                "donotupdate": notUpdate
            }),
            contentType: 'application/json; charset=utf-8',
            async: true,
            processData: false,
            cache: true,
            success: function (data) {
                console.log('success');
            },
            error: function (xhr) {
                console.log('error');
            }
        });
    }
</script>*@


<table class="ui compact table">
    <tr>
        <th>
            Url
        </th>
        <th>
            Имя ссылки
        </th>
        <th>
            Не-обн.
        </th>
        <th>
            Тег
        </th>
        <th>
            Создан
        </th>
        <th class="right aligned"></th>
    </tr>

    @foreach (WebApplication.Models.Feed item in Model)
    {
        <tr>
            <td>
                @Html.Raw(item.Url)
            </td>
            <td style="max-width:150px;">
                @Html.Raw(item.Title)
            </td>
            <td style="max-width:50px;">
                <input name="visible" type="checkbox" @Html.Raw(item.DoNotUpdate ? "checked='checked'" : "") onclick="changeStatus(this)" data-type=@Html.Raw(item.Url)>
            </td>
            <td style="max-width:150px;">
                @Html.ActionLink(item.Tag.Id, "Edit", "Tags", new { id = item.Tag.Id }, null)
            </td>
            <td>
                @Html.Raw(item.CreateDate)
            </td>
            <td class="right aligned">
                @Html.ActionLink("Contents", "ByTag", "Feeds", new { id = item.Tag_Id }, new { @class = "ui teal basic tiny button" })
                @Html.ActionLink("Edit", "Edit", new { url = item.Url }, new { @class = "ui teal basic tiny button" })
            </td>
        </tr>
    }

</table>

<script>
    function changeStatus(el) {
        var url = $(el).attr('data-type');
        var notUpdate = $(el).prop('checked');
        var headers = {};

        $.ajax({
            url: '/Hidden/Feeds/ChangeUpdateStatus',
            dataType: "json",
            type: "POST",
            headers: headers,
            data: JSON.stringify({
                "url": url,
                "donotupdate": notUpdate
            }),
            contentType: 'application/json; charset=utf-8',
            async: true,
            processData: false,
            cache: true,
            success: function (data) {
                console.log('success');
            },
            error: function (xhr) {
                console.log('error');
            }
        });
    }
</script>

Areas/Hidden/Views/Feeds/ByTag.cshtml
@model IEnumerable<WebApplication.Models.Feed>

<table class="ui compact table">
    <tr>
        <th>
            Url
        </th>
        <th>
            Имя ссылки
        </th>
        <th>
            Не-обн.
        </th>
        <th>
            Тег
        </th>
        <th>
            Создан
        </th>
        <th class="right aligned"></th>
    </tr>

    @foreach (WebApplication.Models.Feed item in Model)
    {
        <tr>
            <td>
                @Html.Raw(item.Url)
            </td>
            <td style="max-width:150px;">
                @Html.Raw(item.Title)
            </td>
            <td style="max-width:50px;">
                <input name="visible" type="checkbox" @Html.Raw(item.DoNotUpdate ? "checked='checked'" : "") onclick="changeStatus(this)" data-type=@Html.Raw(item.Url)>
            </td>
            <td style="max-width:150px;">
                @Html.ActionLink(item.Tag.Id, "Edit", "Tags", new { id = item.Tag.Id }, null)
            </td>
            <td>
                @Html.Raw(item.CreateDate)
            </td>
            <td class="right aligned">
                @Html.ActionLink("Contents", "ByTag", "Feeds", new { id = item.Tag_Id }, new { @class = "ui teal basic tiny button" })
                @Html.ActionLink("Edit", "Edit", new { url = item.Url }, new { @class = "ui teal basic tiny button" })
            </td>
        </tr>
    }

</table>

<script>
    function changeStatus(el) {
        var url = $(el).attr('data-type');
        var notUpdate = $(el).prop('checked');
        var headers = {};

        $.ajax({
            url: '/Hidden/Feeds/ChangeUpdateStatus',
            dataType: "json",
            type: "POST",
            headers: headers,
            data: JSON.stringify({
                "url": url,
                "donotupdate": notUpdate
            }),
            contentType: 'application/json; charset=utf-8',
            async: true,
            processData: false,
            cache: true,
            success: function (data) {
                console.log('success');
            },
            error: function (xhr) {
                console.log('error');
            }
        });
    }
</script>



@*<table class="ui compact table">
    <tr>
        <th style="width:400px">
            Url
        </th>
        <th>
            Название
        </th>
        <th>
            Не обновл
        </th>
        <th>
            Язык
        </th>
        <th>
            Проверен
        </th>
        <th>
            Обновлен
        </th>
        <th class="right aligned"></th>
    </tr>

    @foreach (WebApplication.Models.Feed item in Model)
    {
        <tr>
            <td >
                @Html.Raw(item.Url)
            </td>
            <td >
                @Html.Raw(item.Title)
            </td>
            <td>
                <input name="visible" type="checkbox" @Html.Raw(item.DoNotUpdate ? "checked='checked'" : "") onclick="changeStatus(this)" data-type=@Html.Raw(item.Url)>
            </td>
            <td>
                @Html.Raw(item.Language)
            </td>
            <td>
                @Html.Raw(item.LastCheckTime)
            </td>
            <td>
                @Html.Raw(item.LastUpdateTime)
            </td>
            <td class="right aligned">
                @Html.ActionLink("Контент", "ByFeed","Contents", new { url = item.Url }, new { @class = "ui teal basic tiny button" })
                @Html.ActionLink("Изменить", "Edit", new { url = item.Url }, new { @class = "ui teal basic tiny button" })
            </td>
        </tr>
    }

</table>

<script>
    function changeStatus(el) {
        var url = $(el).attr('data-type');
        var notUpdate = $(el).prop('checked');
        var headers = {};

        $.ajax({
            url: '/Hidden/Feeds/ChangeUpdateStatus',
            dataType: "json",
            type: "POST",
            headers: headers,
            data: JSON.stringify({
                "url": url,
                "donotupdate": notUpdate
            }),
            contentType: 'application/json; charset=utf-8',
            async: true,
            processData: false,
            cache: true,
            success: function (data) {
                console.log('success');
            },
            error: function (xhr) {
                console.log('error');
            }
        });
    }
</script>*@

Areas/Hidden/Views/Feeds/Create.cshtml

<h2>Добавить источник</h2>

@if (ViewBag.Message != null)
{
<h3>@Html.Raw(ViewBag.Message)</h3>
}
            @using (Html.BeginForm("Create", "Feeds", FormMethod.Post, new { @class = "ui form" }))
            {
                <div class="three fields">
                    @*<div class="field">
                            <label>http/https</label>
                            <input type="text" name="url"/>
                        </div>*@
                    <div class="field">
                        <label>Url</label>
                        <input type="text" name="url" />
                    </div>
                    <div class="field">
                        <label>Заголовок</label>
                        <input type="text" name="title" />
                    </div>
                </div>
                @*<div class="two fields">
                        <div class="field">
                            <label>Описание</label>
                            @Html.EditorFor(a => a.Description)
                        </div>
                        <div class="field">
                            <label>Комментакий</label>
                            @Html.EditorFor(a => a.Comment)
                        </div>
                    </div>*@

                <div class="two fields">

                    <div class="field">
                        <label>Язык</label>
                        <select class="ui dropdown" name="language">
                            @foreach (WebApplication.Models.Languages lang in ViewBag.Langs)
                            {
                                <option selected="selected" value=@lang.Id>@lang.RussianName</option>
                            }
                        </select>
                    </div>


                    <div class="field">
                        <label>Тег</label>
                        <select class="ui search dropdown" name="tag">
                            @foreach (WebApplication.Models.Tag tag in ViewBag.Tags)
                            {
                                <option selected="selected" value=@tag.Id>@tag.Title</option>
                            }
                        </select>
                    </div>
                </div>
                <div class="fields">
                    <div class="field">
                        <label>Не обновлять</label>
                        @*<input type="checkbox" name="donotupdate" value="false" checked="">Не обновлять автоматичкски<br>*@

                        <input type="radio" name="donotupdate" value="true">Не обновлять автоматичкски<Br>
                        <input type="radio" name="donotupdate" value="false">Обновлять автоматичкски<Br>
                    </div>
                </div>

                <input type="submit" value="Сохранить" class="ui submit button" />
            }

Areas/Hidden/Views/Feeds/Index.cshtml
@model WebApplication.Areas.Hidden.Models.FeedSortParams

@using (Html.BeginForm("Index", "Feeds", FormMethod.Post, new { @class = "ui form" }))
{
    <div class="fields four">
        <div class="field">
            @Html.EditorFor(m => m.Domain, new { htmlAttributes = new { placeholder = "Поиск по домену" } })
        </div>
        <div class="field">
            @Html.EditorFor(m => m.CreationDateStart, new { htmlAttributes = new { type = "text" } })
        </div>
        <div class="field">
            @Html.EditorFor(m => m.CreationDateEnd, new { htmlAttributes = new { type = "text" } })
        </div>
        <div class="field">
            <button class="ui button teal" type="submit">Найти</button>
        </div>
    </div>
    <div class="fields">
        <div class="field">
            <div class="ui toggle checkbox">
                @Html.CheckBoxFor(m => m.DoNotUpdate)
                <label>Не обновлять</label>
            </div>
        </div>
    </div>
}

<div class="ui divider"></div>
<table class="ui compact table">
    <tr>
        <th style="max-width:400px;">
            Url
        </th>
        <th>
            Имя ссылки
        </th>
        <th>
            Не-обн.
        </th>
        <th>
            Тег
        </th>
        <th>
            Создан
        </th>
        <th class="right aligned"></th>
    </tr>

    @foreach (WebApplication.Models.Feed item in ViewBag.Feeds)
    {
        <tr>
            <td >
                @Html.Raw(item.Url)
            </td>
            <td style="max-width:150px;">
                @Html.Raw(item.Title)
            </td>
            <td style="max-width:50px;">
                <input name="visible" type="checkbox" @Html.Raw(item.DoNotUpdate ? "checked='checked'" : "") onclick="changeStatus(this)" data-type=@Html.Raw(item.Url)>
            </td>
            <td style="max-width:150px;">
                @Html.ActionLink(item.Tag.Id, "Edit", "Tags", new { id = item.Tag.Id },null)
            </td>
            <td>
                @Html.Raw(item.CreateDate)
            </td>
            <td class="right aligned">
                @Html.ActionLink("Contents", "ByTag", "Feeds", new { id = item.Tag_Id }, new { @class = "ui teal basic tiny button" })
                @Html.ActionLink("Edit", "Edit", new { url = item.Url }, new { @class = "ui teal basic tiny button" })
            </td>
        </tr>
    }

</table>

<script>
    function changeStatus(el) {
        var url = $(el).attr('data-type');
        var notUpdate = $(el).prop('checked');
        var headers = {};

        $.ajax({
            url: '/Hidden/Feeds/ChangeUpdateStatus',
            dataType: "json",
            type: "POST",
            headers: headers,
            data: JSON.stringify({
                "url": url,
                "donotupdate": notUpdate
            }),
            contentType: 'application/json; charset=utf-8',
            async: true,
            processData: false,
            cache: true,
            success: function (data) {
                console.log('success');
            },
            error: function (xhr) {
                console.log('error');
            }
        });
    }
</script>