Areas/Hidden/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication.Models;
using NLog;

namespace WebApplication.Areas.Hidden.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoriesController : Controller
    {
        private static Logger logger = LogManager.GetCurrentClassLogger();

        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Hidden/Categories
        public async Task<ActionResult> Index(int? current)
        {
            List<Categories> categories = new List<Categories>();
            List<Tag> tags = new List<Tag>();
            if (current.HasValue)
            {
                Categories currentCategory = db.Categories.Include("Tags").FirstOrDefault(a => a.Id == current);
                categories = await db.Categories.Where(a => a.Parent.Id == current.Value).ToListAsync();
                tags = currentCategory.Tags.ToList();
            }
            else
            {
                categories = db.Categories.Where(a=>a.Parent==null).ToList();
            }

            ViewBag.AllTags = db.Tags.Where(a => a.Visible && a.ParentTags.Count == 0).ToList();
            ViewBag.Tags = tags;
            ViewBag.Current = current;
            return View(categories);
        }

        // GET: Hidden/Categories/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categories categories = await db.Categories.FindAsync(id);
            if (categories == null)
            {
                return HttpNotFound();
            }
            return View(categories);
        }

        // GET: Hidden/Categories/Create
        public ActionResult Create(int? parent)
        {
            if (parent.HasValue)
            {
                ViewBag.ParentId = new SelectList(db.Categories.Where(a=>a.Id == parent), "Id", "Name");
            }
            else
            {
                ViewBag.ParentId = new SelectList(db.Categories, "Id", "Name");
            }
            
            return View();
        }

        // POST: Hidden/Categories/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,ParentId")] Categories categories)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(categories);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.ParentId = new SelectList(db.Categories, "Id", "Name", categories.ParentId);
            return View(categories);
        }

        public void AddTag(int categoryId,string tag)
        {
            Categories category = db.Categories.Include("Tags").FirstOrDefault(a => a.Id == categoryId);
            if (category != null && !category.Tags.Any(a=>a.Id == tag))
            {
                Tag tagg = db.Tags.Find(tag);
                if (tagg != null)
                {
                    category.Tags.Add(tagg);
                    db.SaveChanges();
                }
                
            }

            Response.Redirect(Request.UrlReferrer.ToString());
        }

        public void RemoveTag(int categoryId, string tag)
        {
            Categories category = db.Categories.Include("Tags").FirstOrDefault(a => a.Id == categoryId);
            if (category != null && category.Tags.Any(a => a.Id == tag))
            {
                Tag tagg = db.Tags.Find(tag);
                if (tagg != null)
                {
                    category.Tags.Remove(tagg);
                    db.SaveChanges();
                }

            }

            Response.Redirect(Request.UrlReferrer.ToString());
        }

        // GET: Hidden/Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categories categories = db.Categories.Include("Tags").FirstOrDefault(a=>a.Id == id);
            if (categories == null)
            {
                return HttpNotFound();
            }
            ViewBag.ParentId = new SelectList(db.Categories, "Id", "Name", categories.ParentId);

            ViewBag.Tags = db.Tags.Where(a => a.Visible == true).ToList();

            return View(categories);
        }

        // POST: Hidden/Categories/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,ParentId")] Categories categories, string[] tags)
        {
            if (ModelState.IsValid)
            {
                if (categories.ParentId == categories.Id) categories.ParentId = null;

                db.Entry(categories).State = EntityState.Modified;
                Categories cat = db.Categories.Include("Tags").FirstOrDefault(a => a.Id == categories.Id);
                List<Tag> existTag = cat.Tags.ToList();
                existTag.ForEach(a => categories.Tags.Remove(a));

                if(tags != null && tags.Count() > 0)
                {
                    var newTags = db.Tags.Where(a => tags.Contains(a.Id)).ToList<Tag>();
                    newTags.ForEach(a => categories.Tags.Add(a));
                }
                await db.SaveChangesAsync();
                
            }
            ViewBag.ParentId = new SelectList(db.Categories, "Id", "Name", categories.ParentId);
            ViewBag.Tags = db.Tags.Where(a=>a.Visible == true).ToList();
            return View(categories);
        }

        // GET: Hidden/Categories/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categories categories = await db.Categories.FindAsync(id);
            if (categories == null)
            {
                return HttpNotFound();
            }
            return View(categories);
        }

        // POST: Hidden/Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Categories categories = await db.Categories.FindAsync(id);
            db.Categories.Remove(categories);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Hidden/Views/Categories/Create.cshtml
@model WebApplication.Models.Categories

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Categories</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ParentId, "ParentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ParentId", null, htmlAttributes: new { @class = "form-control" },optionLabel:"Родительская категория")
                @Html.ValidationMessageFor(model => model.ParentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Areas/Hidden/Views/Categories/Delete.cshtml
@model WebApplication.Models.Categories

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Categories</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Parent.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Parent.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Areas/Hidden/Views/Categories/Details.cshtml
@model WebApplication.Models.Categories

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Categories</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Parent.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Parent.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Areas/Hidden/Views/Categories/Edit.cshtml
@model WebApplication.Models.Categories

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit","Categories",FormMethod.Post,new { @class = "ui form" }))
{
    @Html.AntiForgeryToken()

    <div class="two fields">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="field">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })

            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })

        </div>

        <div class="field">
            @Html.LabelFor(model => model.ParentId, "ParentId", htmlAttributes: new { @class = "control-label col-md-2" })

            @Html.DropDownList("ParentId",null, "--Выбрать родителя--", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ParentId, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="one field">
        <div class="field">

            <select class="ui fluid search dropdown" multiple="" name="tags">
                <option value="">Включенные тэги</option>
                @foreach (WebApplication.Models.Tag item in ViewBag.Tags)
                {
                    if (Model.Tags.Contains(item))
                    {
                        <option selected="selected" value=@item.Id>@item.Title</option>
                    }
                    else
                    {
                        <option value=@item.Id>@item.Title</option>
                    }
                }
            </select>
        </div>
    </div>
        <div class="field">
            <button class="ui button teal" type="submit">Сохранить</button>
            @Html.ActionLink("К списку", "Index", null, new { @class = "ui button basic teal" })
        </div>
        

        }


Areas/Hidden/Views/Categories/Index.cshtml
@model IEnumerable<WebApplication.Models.Categories>

@{
    ViewBag.Title = "Index";
}

<p>
    @Html.ActionLink("Создать новую категорию", "Create",null,new {@class= "ui teal button" })
    @Html.ActionLink("Сгенерировать новый json для меню", "GenerateMenuJson","Tags",null,new {@class= "ui teal button" })
</p>
<h2>Категории</h2>
<table class="ui teal inverted table">
    <tr>
        <th>
            
        </th>
        @*<th>
            Родительская категория
        </th>*@
        <th class="right aligned"></th>
    </tr>

@foreach (var item in Model) {
    <tr>

        <td>
            @*<h4>@Html.DisplayFor(modelItem => item.Name)</h4>*@
            <h4>@Html.ActionLink(item.Name,"Index", new { current = item.Id }, new { style="color:#fff"})</h4>
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Parent.Name)
        </td>*@
        <td class="right aligned">
            @Html.ActionLink("Редактировать", "Edit", new { id=item.Id }, new { @class = "ui  basic button" }) 
            @Html.ActionLink("Подробности", "Details", new { id=item.Id }, new { @class = "ui  basic button" }) 
            @Html.ActionLink("Удалить", "Delete", new { id=item.Id }, new { @class = "ui  basic button" })
        </td>
    </tr>
}
    @*@Html.ActionLink("Создать новую категорию", "Create", new { parent = ViewBag.Current }, new { @class = "ui teal button" })*@


</table>
@using (Html.BeginForm("Create", "Categories", null, FormMethod.Post, new { @class = "ui form" }))
{
    @Html.AntiForgeryToken()

    <div class="inline field">
        @*@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })*@
        <input value="" placeholder="Имя категории" name="Name" type="text">
        <input type="submit" value="Создать" class="ui teal button" />
    </div>

            <div class="field hidden">
                <input value=@ViewBag.Current name="ParentId" type="text">
                @*@Html.LabelFor(model => model.ParentId, "ParentId", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("ParentId", null, htmlAttributes: new { @class = "form-control" }, optionLabel: "Родительская категория")
                        @Html.ValidationMessageFor(model => model.ParentId, "", new { @class = "text-danger" })
                    </div>*@

            </div>

            
                
            
}

<h2>Теги</h2>
@using (Html.BeginForm("AddTag", "Categories", null, FormMethod.Post, new { @class = "ui form" }))
{
    <select class="ui search dropdown" name="tag">
        <option>Добавить тэг в категорию</option>
        @foreach (WebApplication.Models.Tag item in ViewBag.AllTags)
        {
            <option value=@item.Id>@item.Title</option>
        }
    </select>
    <input type="submit" value="Добавить" class="ui teal button" />
    <div class="field hidden">
        <input value=@ViewBag.Current name="categoryId" type="text">
    </div>
}

<table class="ui teal table">
    @foreach (WebApplication.Models.Tag tag in ViewBag.Tags)
    {
        <tr>
            <td>
                <h4>@Html.ActionLink(tag.Title, "Edit","Tags", new { id = tag.Id })</h4>
            </td>
            
            <td class="right aligned">
                <a href="~/Hidden/Tags/Edit?id=@tag.Id" class="ui button basic teal right">Редактировать</a>
                <a href="~/Hidden/Categories/RemoveTag?categoryId=@ViewBag.Current&tag=@tag.Id" class="ui button basic teal right">Удалить</a>
            </td>
        </tr>
    }
</table>
