Areas/Hidden/Controllers/DomainsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication.Models;
using WebApplication.Areas.Hidden.Models;

namespace WebApplication.Areas.Hidden.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DomainsController : Controller
    {
        
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "Host,Block,Comment,IsNew,AutomaticUpdate,LastUpdateTime,LastListUpdateTime")]Domain domain)
        {
            DateTime now = DateTime.Now;
            domain.LastListUpdateTime = now;
            domain.LastUpdateTime = now;
            domain.CreationDate = now;

            if (ModelState.IsValid)
            {
                ApplicationDbContext db = new ApplicationDbContext();
                db.Domains.Add(domain);
                db.SaveChanges();
            }
            else
            {
                return View(domain);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Index()
        {
            ApplicationDbContext db = new ApplicationDbContext();

            List<Domain> domains = db.Domains.Where(a=>a.CreationDate == DateTime.Now).ToList();
            ViewBag.Domains = domains;

            return View(new DomiansSortParams()
            {
                Name = String.Empty,
                AddingTime = DateTime.Now,
                AutoUpdate = true,
                IsNew = false
            });
        }

        [HttpPost]
        public ActionResult Index([Bind(Include = "Name,IsNew,AutoUpdate,AddingTime")]DomiansSortParams parameters)
        {
            ApplicationDbContext db = new ApplicationDbContext();
            var query = db.Domains.Where(a => a.IsNew == parameters.IsNew && a.AutomaticUpdate == parameters.AutoUpdate);
            if (!String.IsNullOrWhiteSpace(parameters.Name))
            {
                query.Where(a => a.Host.Contains(parameters.Name));
            }

            if (parameters.AddingTime != null)
            {
                query.Where(a => a.CreationDate == parameters.AddingTime);
            }

            ViewBag.Domains = query.ToList();

            return View(parameters);
        }
        
        public bool ChangeDomainsStatus(string domain,bool autoupdate)
        {
            ApplicationDbContext db = new ApplicationDbContext();
            Domain d = db.Domains.Find(domain);
            if (d == null) return false;

            d.AutomaticUpdate = autoupdate;

            db.SaveChanges();
            return true;
        }
    }
}

Areas/Hidden/Controllers/FeedsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication.Areas.Hidden.Models;
using WebApplication.Models;

namespace WebApplication.Areas.Hidden.Controllers
{
    [Authorize(Roles = "Admin")]
    public class FeedsController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Hidden/Feeds
        public ActionResult Index()
        {
            DateTime last = DateTime.Now.AddDays(-2);
            List<Feed> feeds = db.Feeds.Where(a => a.CreateDate >= last && a.DoNotUpdate == false).ToList();
            ViewBag.Feeds = feeds;

            return View(new FeedSortParams()
            {
                Domain = null,
                CreationDateStart = last,
                CreationDateEnd = DateTime.Now,
                DoNotUpdate = false
            });

        }

        [HttpPost]
        public ActionResult Index([Bind(Include = "Domain,CreationDateStart,CreationDateEnd,DoNotUpdate")]FeedSortParams param)
        {
            var query = db.Feeds.Where(a => a.DoNotUpdate == param.DoNotUpdate);

            if (!String.IsNullOrWhiteSpace(param.Domain))
            {
                query = query.Where(a => a.Domain.Host == param.Domain.ToLower());
            }

            if (param.CreationDateStart != null)
            {
                query = query.Where(a => a.CreateDate >= param.CreationDateStart);
            }

            if (param.CreationDateEnd != null)
            {
                query = query.Where(a => a.CreateDate <= param.CreationDateEnd);
            }

            List<Feed> feeds = query.ToList();
            ViewBag.Feeds = feeds;

            return View(param);
        }

        public ActionResult ByTag(string id)
        {

            List<Feed> feeds = db.Feeds.Where(a => a.Tag.Id == id).ToList();
            return View(feeds);
        }

        public ActionResult ByDomain(string host)
        {
            List<Feed> feeds = db.Feeds.Where(a => a.Domain.Host == host).ToList();
            return View(feeds);
        }

        public ActionResult Contents(string url)
        {
            return View(db.Contents.Where(a => a.Feed.Url == url).ToList());
        }

        // GET: Hidden/Feeds/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Hidden/Feeds/Create
        public ActionResult Create()
        {
            ViewBag.Tags = db.Tags.Where(a => a.Visible == true && a.Feeds.Any(b => b.DoNotUpdate == false && a.ParentTags.Count == 0)).ToList();
            ViewBag.Langs = db.Languages.ToList();
            return View();
        }

        [HttpPost]
        public ActionResult Create(string url, string title, string language, bool donotupdate, string tag)
        {
            ViewBag.Tags = db.Tags.Where(a => a.Visible == true && a.Feeds.Any(b => b.DoNotUpdate == false && a.ParentTags.Count == 0)).ToList();
            ViewBag.Langs = db.Languages.ToList();

            if (String.IsNullOrWhiteSpace(url) || String.IsNullOrWhiteSpace(title) || String.IsNullOrWhiteSpace(language) || String.IsNullOrWhiteSpace(tag))
            {
                ViewBag.Message = "Все параметры должны быть заданы";
                return View();
            }

            Uri uri = null;
            if (!Uri.TryCreate(url, UriKind.Absolute, out uri))
            {
                ViewBag.Message = "Невозможно создать Uri";
                return View();
            }

            DateTime now = DateTime.Now;
            Feed newFeed = new Feed();

            newFeed.UriScheme = uri.Scheme;
            newFeed.Url = uri.Host + uri.PathAndQuery;
            newFeed.Title = title;
            newFeed.Language = language;
            newFeed.DoNotUpdate = donotupdate;

            newFeed.LastCheckTime = now;
            newFeed.LastUpdateTime = now;
            newFeed.Rating = 0;
            newFeed.CreateDate = now;
            newFeed.Failures = 0;

            Domain domain = db.Domains.Find(uri.Host);
            if (domain == null)
            {
                ViewBag.Message = String.Format("Домена {0} нет в базе", uri.Host);
                return View();
            }

            Tag existTag = null;

            if (!String.IsNullOrWhiteSpace(tag))
            {
                existTag = db.Tags.FirstOrDefault(a => a.Id == tag);
                if (existTag == null)
                {
                    existTag = db.Tags.Add(new Tag()
                    {
                        Id = tag,
                        CreationDate = now,
                        Title = newFeed.Title,
                        Visible = true
                    });
                }
            }
            else
            {
                return View();
            }

            newFeed.Domain = domain;
            newFeed.Tag = existTag;
            newFeed.TextLanguage = db.Languages.Find(language);

            db.Feeds.Add(newFeed);
            db.SaveChanges();

            ViewBag.Message = String.Format("Источник {0} Успешно добавлен.", uri.AbsoluteUri);
            return View();
        }

        // GET: Hidden/Feeds/Edit/5
        public ActionResult Edit(string url)
        {
            Feed feed = db.Feeds.Find(url);
            ViewBag.Tag = feed.Tag;
            ViewBag.Tags = db.Tags.Where(a => a.Visible == true);
            ViewBag.Languages = db.Languages.ToList();// select new SelectListItem { Text = lang.RussianName, Value = lang.Id };
            return View(feed);
        }

        // POST: Hidden/Feeds/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "Url,Title,Description,Language,Comment,Block,Failures,Rating,DoNotUpdate,Tag_Id")] Feed feed)
        {

            Feed uFeed = db.Feeds.Find(feed.Url);
            uFeed.Title = feed.Title;
            uFeed.Language = feed.Language;
            uFeed.Description = feed.Description;
            uFeed.Comment = feed.Comment;
            uFeed.Block = feed.Block;
            uFeed.Failures = feed.Failures;
            uFeed.Rating = feed.Rating;
            uFeed.Tag_Id = feed.Tag_Id;
            uFeed.Tag = db.Tags.Find(feed.Tag_Id);
            uFeed.DoNotUpdate = feed.DoNotUpdate;
            db.SaveChanges();

            ViewBag.Tag = uFeed.Tag;
            ViewBag.Tags = db.Tags.Where(a => a.Visible == true);
            ViewBag.Languages = db.Languages.ToList();
            return View(feed);
        }

        // GET: Hidden/Feeds/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Hidden/Feeds/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public bool ChangeUpdateStatus(string url,bool doNotUpdate)
        {
            Feed feed = db.Feeds.FirstOrDefault(a => a.Url == url);
            if(feed != null)
            {
                feed.DoNotUpdate = doNotUpdate;
                db.SaveChanges();
                return true;
            }
            return false;
        }
    }
}

Areas/Hidden/Views/Domains/Create.cshtml
@model WebApplication.Models.Domain

@{
    ViewBag.Title = "Create";
}

<h2>Добавить новый домен</h2>

@using (Html.BeginForm("Create","Domains",FormMethod.Post,new { @class= "ui form" }))
{
    @Html.AntiForgeryToken()
    
   
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="three fields">
            <div class="field">
                @Html.LabelFor(model => model.Host, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Host, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Host, "", new { @class = "text-danger" })
            </div>

            <div class="field">
                <label>Комментарий</label>
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="three fields">
            <div class="field">
                <label>Блокировать</label>
                @Html.EditorFor(model => model.Block)
                @Html.ValidationMessageFor(model => model.Block, "", new { @class = "text-danger" })
            </div>



            <div class="field">
                <label>Новый</label>
                @Html.EditorFor(model => model.IsNew)
                @Html.ValidationMessageFor(model => model.IsNew, "", new { @class = "text-danger" })
            </div>

            <div class="field">
                <label>Обновлять автоматически</label>
                @Html.EditorFor(model => model.AutomaticUpdate)
                @Html.ValidationMessageFor(model => model.AutomaticUpdate, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.LastUpdateTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastUpdateTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastUpdateTime, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastListUpdateTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastListUpdateTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastListUpdateTime, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CreationDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreationDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreationDate, "", new { @class = "text-danger" })
                </div>
            </div>*@


                <input type="submit" value="Сохранить" class="ui primary button" />

                <button class="ui button">
                    @Html.ActionLink("К списку", "Index")
                </button>

}

Areas/Hidden/Views/Domains/Index.cshtml
@model WebApplication.Areas.Hidden.Models.DomiansSortParams

@using (Html.BeginForm("Index", "Domains", FormMethod.Post, new { @class = "ui form" }))
{
    <div class="fields three">
        <div class="field">
            @*<label>Название</label>*@

            @Html.EditorFor(m => m.Name, new { htmlAttributes = new { placeholder = "Поиск по названиям" } })
        </div>
        <div class="field">
            @*<label>Сознан позже чем</label>*@
            @*<input type="text" name="CreationDate" placeholder="Сознан позже чем" />*@
            @Html.EditorFor(m => m.AddingTime, new { htmlAttributes = new { type = "text" } })
        </div>
        <div class="field">
            <button class="ui button teal" type="submit">Найти</button>
        </div>
    </div>
    <div class="fields">
        <div class="field">
            <div class="ui toggle checkbox">
                @Html.CheckBoxFor(m => m.AutoUpdate)
                <label>Автоматически обновляется</label>
            </div>
        </div>
        <div class="field">
            <div class="ui toggle checkbox">
                @Html.CheckBoxFor(m => m.IsNew)
                <label>Новый</label>
            </div>
        </div>
    </div>
}

<div class="ui divider"></div>
<table class="ui compact table">
    <tr>
        <th>
            Хост
        </th>
        <th>
            Новый
        </th>
        <th>
            Заблокирован
        </th>
        <th>
            Обновляется
        </th>
        <th>
            Создан
        </th>
        <th class="right aligned"></th>
    </tr>

    @foreach (WebApplication.Models.Domain item in ViewBag.Domains)
    {
        <tr>
            <td style="max-width:150px;">
                @Html.Raw(item.Host)
            </td>
            <td style="max-width:150px;">
                @Html.Raw(item.IsNew)
            </td>
            <td style="max-width:150px;">
                @Html.Raw(item.Block)
            </td>
            <td>

                <input name="visible" type="checkbox" @Html.Raw(item.AutomaticUpdate ? "checked='checked'" : "") onclick="changeStatus(this)" data-type=@Html.Raw(item.Host)>

            </td>
            <td>
                @Html.Raw(item.CreationDate)
            </td>
            <td class="right aligned">
                @Html.ActionLink("Источники", "ByDomain", "Feeds", new { host = item.Host }, new { @class = "ui teal basic tiny button" })
                @*@Html.ActionLink("Изменить", "Edit", new { host = item.Host }, new { @class = "ui teal basic tiny button" })*@
                @*@Html.ActionLink("Подробнее", "Details", new { host = item.Host }, new { @class = "ui teal basic tiny button" })*@
            </td>
        </tr>
    }

</table>

<script>
    function changeStatus(el) {
        var domain = $(el).attr('data-type');
        var update = $(el).prop('checked');
        var headers = {};

        $.ajax({
            url: '/Hidden/Domains/ChangeDomainsStatus',
            dataType: "json",
            type: "POST",
            headers: headers,
            data: JSON.stringify({
                "domain": domain,
                "autoupdate": update
            }),
            contentType: 'application/json; charset=utf-8',
            async: true,
            processData: false,
            cache: true,
            success: function (data) {
                console.log('success');
            },
            error: function (xhr) {
                console.log('error');
            }
        });
    }
</script>